/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelreservationapp;

import java.sql.*;
import static javax.swing.JOptionPane.showMessageDialog;


/**
 *
 * @author Χρήστος
 */
public class MainMenu extends javax.swing.JFrame {

     static Connection con;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    public static Connection getCon() {
        return con;
    }
    
    /**
     * Connect Action JDialog 
     */
    public void connectAction() {
        JDialogConnect connect = new JDialogConnect(this, true);
        connect.setVisible(true);
        
        if (!connect.getUserChoosedOkFlag()) {
            System.out.println("User Pressed Cancel!");
            return;
        }
        
        else {
            System.out.println("User Pressed OK!");
            
            System.out.println("Username: "+ connect.getUsername()); 
            System.out.println("Password: "+ connect.getPassword());      
            System.out.println("Connection String: "+ connect.getConnectionString());
           
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con = DriverManager.getConnection(connect.getConnectionString(), connect.getUsername(), connect.getPassword());
                showMessageDialog(this, "Connected Succesfully!"); 
                jMenuItemConnect.setEnabled(false);
                setActionStatus();
            }

            catch (ClassNotFoundException ex) {
               showMessageDialog(this, ex.getMessage());
            }
            catch (SQLException ex) {
               showMessageDialog(this, ex.getMessage()); 
            }
            
        }  
         
    }   
    
    /**
     * Disconnect Action. 
     */
    public void disconnectAction(){
       try {
            con.close();
            showMessageDialog(this, "Disconnected!");
            jMenuItemConnect.setEnabled(true);
            setActionStatus();
       }
       catch (SQLException ex) {
               showMessageDialog(this, ex.getMessage()); 
       }
    }    
    
     public void setActionStatus(){
        if ( !jMenuItemConnect.isEnabled() ) {
            jMenuItemDisconnect.setEnabled(true);
            jMenu.setEnabled(true);
            jMenuLogIn.setEnabled(true);
            
            
        }
        else {
            jMenuItemDisconnect.setEnabled(false);
            jMenu.setEnabled(false);
            jMenuLogIn.setEnabled(false);
            
          
        }
    }
     
    public void exitAction(){
       this.dispose();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuConnectDB = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemDisconnect = new javax.swing.JMenuItem();
        jMenu = new javax.swing.JMenu();
        jMenuLogIn = new javax.swing.JMenu();
        jMenuItemEmployee = new javax.swing.JMenuItem();
        jMenuItemAdministrator = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Reservation App");
        setBounds(new java.awt.Rectangle(500, 200, 200, 200));
        setResizable(false);

        jMenuConnectDB.setText("ConnectDB");

        jMenuItemConnect.setText("Connect");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenuConnectDB.add(jMenuItemConnect);

        jMenuItemDisconnect.setText("Disconnect");
        jMenuItemDisconnect.setEnabled(false);
        jMenuItemDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisconnectActionPerformed(evt);
            }
        });
        jMenuConnectDB.add(jMenuItemDisconnect);

        jMenuBar.add(jMenuConnectDB);

        jMenu.setText("Menu");
        jMenu.setEnabled(false);
        jMenuBar.add(jMenu);

        jMenuLogIn.setForeground(new java.awt.Color(0, 204, 0));
        jMenuLogIn.setText("Log In");
        jMenuLogIn.setEnabled(false);

        jMenuItemEmployee.setText("Employee");
        jMenuLogIn.add(jMenuItemEmployee);

        jMenuItemAdministrator.setText("Administrator");
        jMenuLogIn.add(jMenuItemAdministrator);

        jMenuBar.add(jMenuLogIn);

        jMenuExit.setForeground(new java.awt.Color(255, 51, 51));
        jMenuExit.setText("Exit");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuExit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1047, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        connectAction();
    }//GEN-LAST:event_jMenuItemConnectActionPerformed

    private void jMenuItemDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisconnectActionPerformed
        disconnectAction();
    }//GEN-LAST:event_jMenuItemDisconnectActionPerformed

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        exitAction();
    }//GEN-LAST:event_jMenuExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConnectDB;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAdministrator;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemDisconnect;
    private javax.swing.JMenuItem jMenuItemEmployee;
    private javax.swing.JMenu jMenuLogIn;
    // End of variables declaration//GEN-END:variables
}
