SELECT * FROM LOGIN;
SELECT * FROM EMPLOYEE;
SELECT * FROM CLIENT;
SELECT * FROM BOOKING;
SELECT * FROM PAYMENT;
SELECT * FROM ROOM;
SELECT * FROM STORAGE;

SELECT * FROM REGISTER;
SELECT * FROM RESERVE;


