SELECT * FROM LOGIN;
SELECT * FROM EMPLOYEE;
SELECT * FROM CLIENT;
SELECT * FROM BOOKING;
SELECT * FROM PAYMENT;
SELECT * FROM ROOM;
SELECT * FROM STORAGE;

SELECT * FROM REGISTER;
SELECT * FROM RESERVE;



--SELECT-- Μας εμφανίζει τον αριθμό κράτησης σε ποιο δωμάτιο ανήκει.
SELECT BOOKING.bID, ROOM.rID
FROM BOOKING
FULL OUTER JOIN ROOM ON BOOKING.roomID=ROOM.rID
ORDER BY BOOKING.bID;



UPDATE ROOM SET rStatus= 'Not Booked' WHERE rID= 7;
UPDATE ROOM SET rStatus= 'Not Booked' WHERE rID= 12;

